version: '3.1'

volumes:
  pg_demo:

services:
  app:
    image: back:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8189:8189"
    depends_on:
      - app-db
    environment:
      - SERVER_PORT= 8189
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db/task_db

  app-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=task_db
    volumes:
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "15432:5432"