server:
  port: 8189
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: POSTGRESQL
    generate-ddl: true
  sql:
    init:
      mode: embedded
      platform: postgres
